include config.mk

all: enhanced_and_extended_suffix_arrays_regenfuss_2020.pdf

enhanced_and_extended_suffix_arrays_regenfuss_2020.pdf: enhanced_and_extended_suffix_arrays_regenfuss_2020.tex
	$(PL) $(PLFLAGS) $<
